import { SOCAL_EXTRA_GYMS } from "./seed-socal";

export type SeedGym = {
  id: string;
  name: string;
  gymType: string;
  address: string;
  city: string;
  lat: number;
  lng: number;
  photoUrl: string;
  description: string;
  amenities: string[];
  hours: string;
  phone: string;
};

export type SeedService = {
  id: string;
  name: string;
  style: string;
  serviceType: string;
  description: string;
  durationMin: number;
  priceCents: number;
};

export type SeedTrainer = {
  id: string;
  gymId: string;
  name: string;
  headline: string;
  bio: string;
  photoUrl: string;
  specialties: string[];
  yearsExp: number;
  rating: number;
  reviewCount: number;
  priceFrom: number;
  city: string;
  lat: number;
  lng: number;
  verified: boolean;
  gallery: string[];
  services: SeedService[];
  availability: { weekday: number; startMin: number; endMin: number }[];
  reviews: { id: string; authorName: string; rating: number; body: string; daysAgo: number }[];
};

const BASE_GYMS: SeedGym[] = [
  {
    id: "wildcard",
    name: "Wildcard Boxing",
    gymType: "boxing",
    address: "1123 E 12th St",
    city: "Los Angeles",
    lat: 34.0407,
    lng: -118.2663,
    photoUrl: "/photos/gyms/boxing-ring.webp",
    description: "Old-school downtown boxing gym. Loud bags, a real ring, and coaches who still hold mitts for a living.",
    amenities: ["Ring", "Heavy bags", "Showers"],
    hours: "Mon–Sat 6am–8pm",
    phone: "(213) 555-0144",
  },
  {
    id: "hayastan",
    name: "Hayastan MMA",
    gymType: "mma",
    address: "Av. Insurgentes Sur 1647",
    city: "Mexico City",
    lat: 19.371,
    lng: -99.1776,
    photoUrl: "/photos/gyms/mma-cage.webp",
    description: "Cage, wrestling mats, and a striking wall. Serious if you put the work in.",
    amenities: ["Cage", "Wrestling mats", "Strength corner"],
    hours: "Mon–Fri 7am–10pm, Sat 8am–4pm",
    phone: "+52 55 5550 0190",
  },
  {
    id: "gracie-wla",
    name: "Gracie Barra West London",
    gymType: "bjj",
    address: "18 Battersea Park Rd",
    city: "London",
    lat: 51.475,
    lng: -0.1445,
    photoUrl: "/photos/gyms/bjj-mats.webp",
    description: "Gi-first academy. Clean mats, structured curriculum, private rooms for one-on-ones.",
    amenities: ["Gi rental", "Changing rooms", "Kids classes"],
    hours: "Mon–Fri 6am–9pm, Sat–Sun 8am–2pm",
    phone: "+44 20 7946 0162",
  },
  {
    id: "alliance-sd",
    name: "Alliance Jiu-Jitsu Miami",
    gymType: "bjj",
    address: "1750 N Bayshore Dr",
    city: "Miami",
    lat: 25.7906,
    lng: -80.186,
    photoUrl: "/photos/gyms/bjj-mats.webp",
    description: "Competition-minded no-gi and gi room. Great for wrestlers crossing over to submissions.",
    amenities: ["Competition team", "Open mat Sunday", "Sauna"],
    hours: "Mon–Sat 6am–9pm",
    phone: "(305) 555-0118",
  },
  {
    id: "temecula-box",
    name: "Fifth Ward Boxing",
    gymType: "boxing",
    address: "3300 Lyons Ave",
    city: "Houston",
    lat: 29.7805,
    lng: -95.326,
    photoUrl: "/photos/gyms/boxing-ring.webp",
    description: "Houston boxing gym with a loud bag line and a coach who lives on the mitts.",
    amenities: ["Ring", "Outdoor bags", "Parking"],
    hours: "Mon–Fri 5:30am–8:30pm, Sat 8am–1pm",
    phone: "(713) 555-0177",
  },
  {
    id: "ufc-cm",
    name: "UFC Gym Brickell",
    gymType: "mma",
    address: "888 Brickell Ave",
    city: "Miami",
    lat: 25.765,
    lng: -80.191,
    photoUrl: "/photos/gyms/training.webp",
    description: "Full combat-and-fitness floor: bags, mats, turf, and a cage.",
    amenities: ["Cage", "Turf", "Lockers", "Classes"],
    hours: "Open 5am–11pm daily",
    phone: "(305) 555-0133",
  },
  {
    id: "golds-venice",
    name: "Gold's Gym Venice",
    gymType: "strength",
    address: "360 Hampton Dr",
    city: "Venice",
    lat: 33.9879,
    lng: -118.4705,
    photoUrl: "/photos/gyms/weights.webp",
    description: "The Mecca. Bodybuilding floor, posing room, and coaches who still count plates.",
    amenities: ["Free weights", "Posing room", "Juice bar"],
    hours: "Open 4am–midnight",
    phone: "(310) 555-0121",
  },
  {
    id: "tenth-planet",
    name: "10th Planet Jiu-Jitsu NYC",
    gymType: "bjj",
    address: "265 W 37th St",
    city: "New York",
    lat: 40.7536,
    lng: -73.9918,
    photoUrl: "/photos/gyms/bjj-mats.webp",
    description: "No-gi headquarters energy. Lockdowns, rubber guard, and private sessions.",
    amenities: ["No-gi only", "Open mat", "Video room"],
    hours: "Mon–Sat 7am–9pm",
    phone: "(212) 555-0188",
  },
  {
    id: "oc-wrestling",
    name: "Chicago Regional Wrestling",
    gymType: "wrestling",
    address: "2301 W Belmont Ave",
    city: "Chicago",
    lat: 41.9396,
    lng: -87.685,
    photoUrl: "/photos/gyms/wrestling.webp",
    description: "Folkstyle, freestyle, and Greco room used by high-schoolers and adults coming back to the mat.",
    amenities: ["Wall mats", "Throw dummy", "Film TV"],
    hours: "Mon–Fri 4pm–9pm, Sat 9am–1pm",
    phone: "(773) 555-0104",
  },
  {
    id: "sityodtong",
    name: "Sityodtong Bangkok",
    gymType: "muay-thai",
    address: "88 Rama IX Rd",
    city: "Bangkok",
    lat: 13.7437,
    lng: 100.5622,
    photoUrl: "/photos/gyms/martial-arts.webp",
    description: "Thai pads, teep bags, and a ring. Clinch work that doesn't pretend it's kickboxing.",
    amenities: ["Thai pads", "Ring", "Shin guard rental"],
    hours: "Mon–Sat 7am–9pm",
    phone: "+66 2 555 0155",
  },
  {
    id: "iron-temple",
    name: "Iron Temple",
    gymType: "strength",
    address: "220 12th Ave",
    city: "New York",
    lat: 40.7506,
    lng: -74.007,
    photoUrl: "/photos/gyms/strength.webp",
    description: "Powerlifting and athletic strength. Platforms, specialty bars, and coaches who program.",
    amenities: ["Platforms", "Specialty bars", "Recovery room"],
    hours: "Mon–Fri 6am–8pm, Sat 8am–2pm",
    phone: "(212) 555-0199",
  },
  {
    id: "torrance-shotokan",
    name: "Tokyo Shotokan",
    gymType: "karate",
    address: "1-2-3 Shibuya",
    city: "Tokyo",
    lat: 35.658,
    lng: 139.7016,
    photoUrl: "/photos/gyms/martial-arts.webp",
    description: "Traditional Shotokan dojo. Quiet, precise, no music.",
    amenities: ["Wood floor", "Mirrors", "Weapons rack"],
    hours: "Mon–Thu 5pm–9pm, Sat 9am–1pm",
    phone: "+81 3 5550 0170",
  },
  {
    id: "escondido-wrestle",
    name: "Toronto Wrestling Club",
    gymType: "wrestling",
    address: "675 Queen St W",
    city: "Toronto",
    lat: 43.647,
    lng: -79.4026,
    photoUrl: "/photos/gyms/wrestling.webp",
    description: "Toronto wrestling club. Takedowns, mat returns, and live go until the whistle.",
    amenities: ["Mats", "Team nights", "Parking"],
    hours: "Mon–Fri 5pm–8:30pm, Sat 8am–12pm",
    phone: "(416) 555-0128",
  },
  {
    id: "still-point",
    name: "Still Point Mobility",
    gymType: "fitness",
    address: "12 Foveaux St",
    city: "Sydney",
    lat: -33.8832,
    lng: 151.2095,
    photoUrl: "/photos/gyms/gym-dark.webp",
    description: "Quiet studio for fighters who need hips, spines, and necks that still work on Monday.",
    amenities: ["Yoga mats", "Bolsters", "Infrared"],
    hours: "Tue–Sat 7am–7pm",
    phone: "+61 2 5550 0142",
  },
  {
    id: "socal-temecula",
    name: "Temecula Boxing Club",
    gymType: "boxing",
    address: "27645 Jefferson Ave",
    city: "Temecula",
    lat: 33.4936,
    lng: -117.1484,
    photoUrl: "/photos/gyms/boxing-ring.webp",
    description: "Inland Empire boxing gym with a loud bag line and a coach who lives on the mitts.",
    amenities: ["Ring", "Outdoor bags", "Parking"],
    hours: "Mon–Fri 5:30am–8:30pm, Sat 8am–1pm",
    phone: "(951) 555-0177",
  },
  {
    id: "socal-alliance",
    name: "Alliance Jiu-Jitsu San Diego",
    gymType: "bjj",
    address: "1235 Hotel Circle S",
    city: "San Diego",
    lat: 32.76,
    lng: -117.1674,
    photoUrl: "/photos/gyms/bjj-mats.webp",
    description: "Competition-minded no-gi and gi room in Mission Valley.",
    amenities: ["Competition team", "Open mat Sunday", "Sauna"],
    hours: "Mon–Sat 6am–9pm",
    phone: "(619) 555-0118",
  },
  {
    id: "socal-ufc",
    name: "UFC Gym Costa Mesa",
    gymType: "mma",
    address: "1835 Newport Blvd",
    city: "Costa Mesa",
    lat: 33.6411,
    lng: -117.9187,
    photoUrl: "/photos/gyms/training.webp",
    description: "Full combat-and-fitness floor: bags, mats, turf, and a cage.",
    amenities: ["Cage", "Turf", "Lockers", "Classes"],
    hours: "Open 5am–11pm daily",
    phone: "(714) 555-0133",
  },
  {
    id: "socal-hayastan",
    name: "Hayastan MMA North Hollywood",
    gymType: "mma",
    address: "5655 Vineland Ave",
    city: "North Hollywood",
    lat: 34.1735,
    lng: -118.3704,
    photoUrl: "/photos/gyms/mma-cage.webp",
    description: "Valley MMA room with a cage, wrestling mats, and a striking wall.",
    amenities: ["Cage", "Wrestling mats", "Strength corner"],
    hours: "Mon–Fri 7am–10pm, Sat 8am–4pm",
    phone: "(818) 555-0190",
  },
  {
    id: "socal-gracie",
    name: "Gracie Barra West LA",
    gymType: "bjj",
    address: "12121 W Pico Blvd",
    city: "Los Angeles",
    lat: 34.0289,
    lng: -118.4568,
    photoUrl: "/photos/gyms/bjj-mats.webp",
    description: "Gi-first academy on the Westside.",
    amenities: ["Gi rental", "Changing rooms", "Kids classes"],
    hours: "Mon–Fri 6am–9pm, Sat–Sun 8am–2pm",
    phone: "(310) 555-0162",
  },
  {
    id: "socal-tenth",
    name: "10th Planet Jiu-Jitsu LA",
    gymType: "bjj",
    address: "1411 N La Brea Ave",
    city: "Hollywood",
    lat: 34.0962,
    lng: -118.3445,
    photoUrl: "/photos/gyms/bjj-mats.webp",
    description: "No-gi headquarters energy in Hollywood.",
    amenities: ["No-gi only", "Open mat", "Video room"],
    hours: "Mon–Sat 7am–9pm",
    phone: "(323) 555-0188",
  },
  {
    id: "socal-ocw",
    name: "OC Regional Wrestling",
    gymType: "wrestling",
    address: "2100 N Broadway",
    city: "Santa Ana",
    lat: 33.7644,
    lng: -117.8677,
    photoUrl: "/photos/gyms/wrestling.webp",
    description: "Folkstyle, freestyle, and Greco room.",
    amenities: ["Wall mats", "Throw dummy", "Film TV"],
    hours: "Mon–Fri 4pm–9pm, Sat 9am–1pm",
    phone: "(714) 555-0104",
  },
  {
    id: "socal-sityodtong",
    name: "Sityodtong Hollywood",
    gymType: "muay-thai",
    address: "1640 N Cherokee Ave",
    city: "Hollywood",
    lat: 34.1016,
    lng: -118.3348,
    photoUrl: "/photos/gyms/martial-arts.webp",
    description: "Thai pads, teep bags, and a ring.",
    amenities: ["Thai pads", "Ring", "Shin guard rental"],
    hours: "Mon–Sat 7am–9pm",
    phone: "(323) 555-0155",
  },
  {
    id: "socal-iron",
    name: "Iron Temple Strength",
    gymType: "strength",
    address: "17875 Sky Park Circle",
    city: "Irvine",
    lat: 33.6472,
    lng: -117.8392,
    photoUrl: "/photos/gyms/strength.webp",
    description: "Powerlifting and athletic strength in Irvine.",
    amenities: ["Platforms", "Specialty bars", "Recovery room"],
    hours: "Mon–Fri 6am–8pm, Sat 8am–2pm",
    phone: "(949) 555-0199",
  },
  {
    id: "socal-shotokan",
    name: "Torrance Shotokan",
    gymType: "karate",
    address: "2235 W Carson St",
    city: "Torrance",
    lat: 33.8303,
    lng: -118.3244,
    photoUrl: "/photos/gyms/martial-arts.webp",
    description: "Traditional Shotokan dojo with adult beginners and dan-rank privates.",
    amenities: ["Wood floor", "Mirrors", "Weapons rack"],
    hours: "Mon–Thu 5pm–9pm, Sat 9am–1pm",
    phone: "(310) 555-0170",
  },
  {
    id: "socal-escondido",
    name: "Escondido Wrestling Club",
    gymType: "wrestling",
    address: "420 N Broadway",
    city: "Escondido",
    lat: 33.1242,
    lng: -117.0814,
    photoUrl: "/photos/gyms/wrestling.webp",
    description: "North County wrestling club.",
    amenities: ["Mats", "Team nights", "Parking"],
    hours: "Mon–Fri 5pm–8:30pm, Sat 8am–12pm",
    phone: "(760) 555-0128",
  },
  {
    id: "socal-still",
    name: "Still Point Pasadena",
    gymType: "fitness",
    address: "35 S Raymond Ave",
    city: "Pasadena",
    lat: 34.146,
    lng: -118.1487,
    photoUrl: "/photos/gyms/gym-dark.webp",
    description: "Quiet studio for fighters who need hips, spines, and necks that still work on Monday.",
    amenities: ["Yoga mats", "Bolsters", "Infrared"],
    hours: "Tue–Sat 7am–7pm",
    phone: "(626) 555-0142",
  },
];

export const SEED_GYMS: SeedGym[] = [...BASE_GYMS, ...SOCAL_EXTRA_GYMS];

function svc(
  id: string,
  name: string,
  style: string,
  serviceType: string,
  description: string,
  durationMin: number,
  priceCents: number,
): SeedService {
  return { id, name, style, serviceType, description, durationMin, priceCents };
}

function weekdays(startHour = 16, endHour = 20) {
  return [1, 2, 3, 4, 5].map((weekday) => ({
    weekday,
    startMin: startHour * 60,
    endMin: endHour * 60,
  }));
}

function gymOf(id: string) {
  const g = BASE_GYMS.find((x) => x.id === id);
  if (!g) throw new Error(`missing gym ${id}`);
  return g;
}

function trainer(
  partial: Omit<SeedTrainer, "availability" | "city" | "lat" | "lng" | "priceFrom" | "verified"> & {
    gymId: string;
    availability?: SeedTrainer["availability"];
  },
): SeedTrainer {
  const g = gymOf(partial.gymId);
  return {
    ...partial,
    city: g.city,
    lat: g.lat,
    lng: g.lng,
    verified: true,
    priceFrom: Math.min(...partial.services.map((s) => s.priceCents)),
    availability: partial.availability ?? weekdays(),
  };
}

export const SEED_TRAINERS: SeedTrainer[] = [
  trainer({
    id: "marcus",
    gymId: "wildcard",
    name: "Marcus Hale",
    headline: "Pad holding for strikers. No reels.",
    bio: "Twelve years in the gym, six as a full-time mittman. I run rounds like a fight: clean shots, feet moving, no leaning on the bags. If you want a workout playlist, this is not that room.",
    photoUrl: "/photos/trainers/marcus.webp",
    specialties: ["boxing", "mittwork"],
    yearsExp: 12,
    rating: 4.9,
    reviewCount: 48,
    gallery: ["/photos/gyms/boxing-ring.webp", "/photos/gyms/training.webp", "/photos/gyms/martial-arts.webp"],
    services: [
      svc("marcus-mitt", "Mittwork rounds", "boxing", "mittwork", "6–8 hard rounds on the pads.", 60, 8500),
      svc("marcus-priv", "Boxing private", "boxing", "one-on-one", "Footwork, jab, and bag work.", 60, 7500),
    ],
    reviews: [
      { id: "rv-m1", authorName: "Chris P.", rating: 5, body: "Best pad round I've had in LA.", daysAgo: 12 },
      { id: "rv-m2", authorName: "Alina V.", rating: 5, body: "He actually teaches. Not just a sweat.", daysAgo: 40 },
    ],
  }),
  trainer({
    id: "jamal",
    gymId: "wildcard",
    name: "Jamal Reyes",
    headline: "Amateur boxers and first-timers. Same standard.",
    bio: "I came up at Wildcard and still train here. I like beginners who listen and amateurs who need a sparring plan, not a montage.",
    photoUrl: "/photos/trainers/jamal.webp",
    specialties: ["boxing"],
    yearsExp: 8,
    rating: 4.8,
    reviewCount: 31,
    gallery: ["/photos/gyms/boxing-ring.webp", "/photos/gyms/gym-dark.webp"],
    services: [svc("jamal-box", "Boxing private", "boxing", "one-on-one", "Fundamentals and spar prep.", 60, 6500)],
    reviews: [{ id: "rv-j1", authorName: "Nate", rating: 5, body: "Patient but not soft.", daysAgo: 8 }],
  }),
  trainer({
    id: "sofia",
    gymId: "sityodtong",
    name: "Sofia Prasert",
    headline: "Thai pads and clinch. No cardio kickboxing.",
    bio: "Raised in the Sityodtong room. I hold pads the way my coaches held them for me — straight, mean, and on time.",
    photoUrl: "/photos/trainers/sofia.webp",
    specialties: ["muay-thai"],
    yearsExp: 10,
    rating: 4.9,
    reviewCount: 39,
    gallery: ["/photos/gyms/martial-arts.webp", "/photos/gyms/training.webp"],
    services: [svc("sofia-pads", "Thai pad session", "muay-thai", "mittwork", "Clinch, teep, kicks, and pads.", 60, 7000)],
    reviews: [{ id: "rv-s1", authorName: "Bee", rating: 5, body: "Legs were cooked. Perfect.", daysAgo: 21 }],
  }),
  trainer({
    id: "kenji",
    gymId: "torrance-shotokan",
    name: "Kenji Okada",
    headline: "Shotokan for adults. Quiet dojo.",
    bio: "Dan-rank instruction without the kid-class chaos. Kihon, kata, and controlled kumite.",
    photoUrl: "/photos/trainers/kenji.webp",
    specialties: ["karate"],
    yearsExp: 20,
    rating: 4.7,
    reviewCount: 18,
    gallery: ["/photos/gyms/martial-arts.webp"],
    services: [svc("kenji-kata", "Karate private", "karate", "one-on-one", "Form, timing, and distance.", 60, 6000)],
    reviews: [{ id: "rv-k1", authorName: "Marta", rating: 5, body: "Exactly the traditional room I wanted.", daysAgo: 33 }],
  }),
  trainer({
    id: "andre",
    gymId: "hayastan",
    name: "Andre Petrosyan",
    headline: "Wrestling into MMA. Cage IQ.",
    bio: "Freestyle base, MMA finish. I drill takedowns that stick when someone is hitting you back.",
    photoUrl: "/photos/trainers/andre.webp",
    specialties: ["mma", "wrestling"],
    yearsExp: 14,
    rating: 4.8,
    reviewCount: 27,
    gallery: ["/photos/gyms/mma-cage.webp", "/photos/gyms/training.webp"],
    services: [svc("andre-mma", "MMA private", "mma", "one-on-one", "Takedowns, cage work, striking entries.", 60, 9000)],
    reviews: [{ id: "rv-a1", authorName: "Luis", rating: 5, body: "My shot is actually a shot now.", daysAgo: 15 }],
  }),
  trainer({
    id: "elena",
    gymId: "gracie-wla",
    name: "Elena Costa",
    headline: "Gi fundamentals. Purple belt and up welcome too.",
    bio: "I teach a tight closed-guard game and a passing system you can remember on a bad day.",
    photoUrl: "/photos/trainers/elena.webp",
    specialties: ["bjj"],
    yearsExp: 9,
    rating: 4.9,
    reviewCount: 44,
    gallery: ["/photos/gyms/bjj-mats.webp"],
    services: [svc("elena-gi", "BJJ private", "bjj", "one-on-one", "Gi positional sparring and drilling.", 60, 8000)],
    reviews: [{ id: "rv-e1", authorName: "Sam", rating: 5, body: "Best private I've bought.", daysAgo: 6 }],
  }),
  trainer({
    id: "dario",
    gymId: "oc-wrestling",
    name: "Dario Chen",
    headline: "Folkstyle and freestyle. Adults welcome.",
    bio: "College wrestler. I run live go, hand-fighting, and mat returns until the whistle.",
    photoUrl: "/photos/trainers/dario.webp",
    specialties: ["wrestling"],
    yearsExp: 11,
    rating: 4.6,
    reviewCount: 16,
    gallery: ["/photos/gyms/wrestling.webp", "/photos/gyms/mma-cage.webp"],
    services: [svc("dario-live", "Wrestling private", "wrestling", "grappling-drills", "Hand fighting and live wrestling.", 60, 6500)],
    reviews: [{ id: "rv-d1", authorName: "Coach Ray", rating: 5, body: "Brought my kid. Dario is legit.", daysAgo: 18 }],
  }),
  trainer({
    id: "amina",
    gymId: "iron-temple",
    name: "Amina Brooks",
    headline: "Strength that transfers to a fight.",
    bio: "I program for strikers and grapplers: posterior chain, neck, and hips — not beach selfies.",
    photoUrl: "/photos/trainers/amina.webp",
    specialties: ["strength", "bodybuilding"],
    yearsExp: 7,
    rating: 4.8,
    reviewCount: 22,
    gallery: ["/photos/gyms/strength.webp", "/photos/gyms/weights.webp"],
    services: [svc("amina-str", "Strength session", "strength", "strength", "Lift programmed for your fight camp.", 60, 7000)],
    reviews: [{ id: "rv-am1", authorName: "Theo", rating: 5, body: "My double-leg doesn't die in round three.", daysAgo: 9 }],
  }),
  trainer({
    id: "tyrell",
    gymId: "temecula-box",
    name: "Tyrell Nash",
    headline: "Old-school mitts. Houston heat.",
    bio: "I came up in rec-center boxing and still teach it that way: jab, feet, chin down.",
    photoUrl: "/photos/trainers/tyrell.webp",
    specialties: ["boxing"],
    yearsExp: 15,
    rating: 4.7,
    reviewCount: 29,
    gallery: ["/photos/gyms/boxing-ring.webp", "/photos/gyms/training.webp"],
    services: [svc("tyrell-mitt", "Mittwork session", "boxing", "mittwork", "Hard pad rounds.", 60, 5500)],
    reviews: [{ id: "rv-t1", authorName: "Dee", rating: 5, body: "No nonsense. I'll be back.", daysAgo: 4 }],
  }),
  trainer({
    id: "lucia",
    gymId: "alliance-sd",
    name: "Lucia Mendes",
    headline: "No-gi pressure passing.",
    bio: "Competition blue-to-brown path. I like wrestlers who want submissions without losing their takedown.",
    photoUrl: "/photos/trainers/lucia.webp",
    specialties: ["bjj", "grappling"],
    yearsExp: 8,
    rating: 4.8,
    reviewCount: 25,
    gallery: ["/photos/gyms/bjj-mats.webp", "/photos/gyms/wrestling.webp"],
    services: [svc("lucia-nogi", "No-gi private", "grappling", "grappling-drills", "Passing and pin attacks.", 60, 7500)],
    reviews: [{ id: "rv-l1", authorName: "Omar", rating: 5, body: "Pressure is a skill. She teaches it.", daysAgo: 11 }],
  }),
  trainer({
    id: "ryan",
    gymId: "golds-venice",
    name: "Ryan Cole",
    headline: "Bodybuilding that still lets you walk.",
    bio: "Venice floor, old-school splits, and posing if you want it. I'll also keep your shoulders in their sockets.",
    photoUrl: "/photos/trainers/ryan.webp",
    specialties: ["bodybuilding", "strength"],
    yearsExp: 9,
    rating: 4.6,
    reviewCount: 19,
    gallery: ["/photos/gyms/weights.webp", "/photos/gyms/strength.webp"],
    services: [svc("ryan-bb", "Bodybuilding private", "bodybuilding", "one-on-one", "Hypertrophy session on the floor.", 60, 8000)],
    reviews: [{ id: "rv-r1", authorName: "Gina", rating: 5, body: "He actually watches your form.", daysAgo: 27 }],
  }),
  trainer({
    id: "maya",
    gymId: "still-point",
    name: "Maya Singh",
    headline: "Hips, spines, necks. Fighters welcome.",
    bio: "Yoga and mobility for people who get hit. Breath work that doesn't feel like a retreat flyer.",
    photoUrl: "/photos/trainers/maya.webp",
    specialties: ["yoga", "fitness"],
    yearsExp: 6,
    rating: 4.9,
    reviewCount: 33,
    gallery: ["/photos/gyms/training.webp", "/photos/gyms/weights.webp"],
    services: [svc("maya-mob", "Mobility private", "yoga", "one-on-one", "Restore after hard rounds.", 60, 6000)],
    reviews: [{ id: "rv-my1", authorName: "Jess", rating: 5, body: "I can turn my head again.", daysAgo: 3 }],
  }),
  trainer({
    id: "hector",
    gymId: "escondido-wrestle",
    name: "Hector Ruiz",
    headline: "Freestyle attacks. Adults and high school.",
    bio: "I run a hard room with a clock and a whistle. If you want to wrestle, we wrestle.",
    photoUrl: "/photos/trainers/hector.webp",
    specialties: ["wrestling"],
    yearsExp: 13,
    rating: 4.7,
    reviewCount: 14,
    gallery: ["/photos/gyms/wrestling.webp"],
    services: [svc("hector-fs", "Freestyle private", "wrestling", "grappling-drills", "Attacks, defense, live.", 60, 6000)],
    reviews: [{ id: "rv-h1", authorName: "Will", rating: 5, body: "Gas tank went through the roof.", daysAgo: 22 }],
  }),
  trainer({
    id: "nora",
    gymId: "still-point",
    name: "Nora Ellis",
    headline: "General fitness with a combat bias.",
    bio: "Not a fight coach. I get fighters and regular people strong, lean, and able to train tomorrow.",
    photoUrl: "/photos/trainers/nora.webp",
    specialties: ["fitness"],
    yearsExp: 5,
    rating: 4.8,
    reviewCount: 21,
    gallery: ["/photos/gyms/gym-dark.webp"],
    services: [svc("nora-fit", "Fitness private", "fitness", "one-on-one", "Conditioning and strength mix.", 45, 5500)],
    reviews: [{ id: "rv-n1", authorName: "Pat", rating: 5, body: "Hard without being stupid.", daysAgo: 14 }],
  }),
  trainer({
    id: "priya",
    gymId: "ufc-cm",
    name: "Priya Shah",
    headline: "Striking for MMA. Cage entries.",
    bio: "Kickboxing base, MMA timing. I like people who want to chain strikes into takedowns.",
    photoUrl: "/photos/trainers/priya.webp",
    specialties: ["mma", "muay-thai"],
    yearsExp: 7,
    rating: 4.7,
    reviewCount: 17,
    gallery: ["/photos/gyms/mma-cage.webp", "/photos/gyms/martial-arts.webp"],
    services: [svc("priya-mma", "MMA striking private", "mma", "one-on-one", "Combos into clinch and shots.", 60, 8000)],
    reviews: [{ id: "rv-p1", authorName: "Andre G.", rating: 4, body: "Tough pads. Worth it.", daysAgo: 19 }],
  }),
  trainer({
    id: "cole",
    gymId: "tenth-planet",
    name: "Cole Winters",
    headline: "No-gi system. Rubber guard optional.",
    bio: "10th Planet lineage. I teach a system, not a pile of moves you forget on Monday.",
    photoUrl: "/photos/trainers/cole.webp",
    specialties: ["bjj", "grappling"],
    yearsExp: 10,
    rating: 4.8,
    reviewCount: 28,
    gallery: ["/photos/gyms/bjj-mats.webp"],
    services: [svc("cole-10p", "No-gi system private", "grappling", "one-on-one", "Lockdown, passing, submissions.", 60, 8500)],
    reviews: [{ id: "rv-c1", authorName: "Kim", rating: 5, body: "Finally a private with a plan.", daysAgo: 7 }],
  }),
];
