/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ApiPlaceThumbRouteImport } from './routes/api/place-thumb'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as GymsIdRouteImport } from './routes/gyms/$id'
import { Route as InboxBookingIdRouteImport } from './routes/inbox.$bookingId'
import { Route as TrainersIdRouteImport } from './routes/trainers/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMediaNameRouteImport } from './routes/api/media.$name'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlaceThumbRoute = ApiPlaceThumbRouteImport.update({
  id: '/api/place-thumb',
  path: '/api/place-thumb',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const GymsIdRoute = GymsIdRouteImport.update({
  id: '/gyms/$id',
  path: '/gyms/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxBookingIdRoute = InboxBookingIdRouteImport.update({
  id: '/$bookingId',
  path: '/$bookingId',
  getParentRoute: () => InboxRoute,
} as any)
const TrainersIdRoute = TrainersIdRouteImport.update({
  id: '/trainers/$id',
  path: '/trainers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaNameRoute = ApiMediaNameRouteImport.update({
  id: '/api/media/$name',
  path: '/api/media/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bookings': typeof BookingsRoute
  '/dashboard': typeof DashboardRoute
  '/earnings': typeof EarningsRoute
  '/inbox': typeof InboxRouteWithChildren
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/onboard': typeof OnboardRoute
  '/search': typeof SearchRoute
  '/api/place-thumb': typeof ApiPlaceThumbRoute
  '/api/upload': typeof ApiUploadRoute
  '/gyms/$id': typeof GymsIdRoute
  '/inbox/$bookingId': typeof InboxBookingIdRoute
  '/trainers/$id': typeof TrainersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$name': typeof ApiMediaNameRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bookings': typeof BookingsRoute
  '/dashboard': typeof DashboardRoute
  '/earnings': typeof EarningsRoute
  '/inbox': typeof InboxRouteWithChildren
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/onboard': typeof OnboardRoute
  '/search': typeof SearchRoute
  '/api/place-thumb': typeof ApiPlaceThumbRoute
  '/api/upload': typeof ApiUploadRoute
  '/gyms/$id': typeof GymsIdRoute
  '/inbox/$bookingId': typeof InboxBookingIdRoute
  '/trainers/$id': typeof TrainersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$name': typeof ApiMediaNameRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bookings': typeof BookingsRoute
  '/dashboard': typeof DashboardRoute
  '/earnings': typeof EarningsRoute
  '/inbox': typeof InboxRouteWithChildren
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/onboard': typeof OnboardRoute
  '/search': typeof SearchRoute
  '/api/place-thumb': typeof ApiPlaceThumbRoute
  '/api/upload': typeof ApiUploadRoute
  '/gyms/$id': typeof GymsIdRoute
  '/inbox/$bookingId': typeof InboxBookingIdRoute
  '/trainers/$id': typeof TrainersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$name': typeof ApiMediaNameRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/bookings'
    | '/dashboard'
    | '/earnings'
    | '/inbox'
    | '/login'
    | '/map'
    | '/onboard'
    | '/search'
    | '/api/place-thumb'
    | '/api/upload'
    | '/gyms/$id'
    | '/inbox/$bookingId'
    | '/trainers/$id'
    | '/api/auth/$'
    | '/api/media/$name'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/bookings'
    | '/dashboard'
    | '/earnings'
    | '/inbox'
    | '/login'
    | '/map'
    | '/onboard'
    | '/search'
    | '/api/place-thumb'
    | '/api/upload'
    | '/gyms/$id'
    | '/inbox/$bookingId'
    | '/trainers/$id'
    | '/api/auth/$'
    | '/api/media/$name'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/bookings'
    | '/dashboard'
    | '/earnings'
    | '/inbox'
    | '/login'
    | '/map'
    | '/onboard'
    | '/search'
    | '/api/place-thumb'
    | '/api/upload'
    | '/gyms/$id'
    | '/inbox/$bookingId'
    | '/trainers/$id'
    | '/api/auth/$'
    | '/api/media/$name'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BookingsRoute: typeof BookingsRoute
  DashboardRoute: typeof DashboardRoute
  EarningsRoute: typeof EarningsRoute
  InboxRoute: typeof InboxRouteWithChildren
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  OnboardRoute: typeof OnboardRoute
  SearchRoute: typeof SearchRoute
  ApiPlaceThumbRoute: typeof ApiPlaceThumbRoute
  ApiUploadRoute: typeof ApiUploadRoute
  GymsIdRoute: typeof GymsIdRoute
  TrainersIdRoute: typeof TrainersIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMediaNameRoute: typeof ApiMediaNameRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/place-thumb': {
      id: '/api/place-thumb'
      path: '/api/place-thumb'
      fullPath: '/api/place-thumb'
      preLoaderRoute: typeof ApiPlaceThumbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gyms/$id': {
      id: '/gyms/$id'
      path: '/gyms/$id'
      fullPath: '/gyms/$id'
      preLoaderRoute: typeof GymsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/$bookingId': {
      id: '/inbox/$bookingId'
      path: '/$bookingId'
      fullPath: '/inbox/$bookingId'
      preLoaderRoute: typeof InboxBookingIdRouteImport
      parentRoute: typeof InboxRoute
    }
    '/trainers/$id': {
      id: '/trainers/$id'
      path: '/trainers/$id'
      fullPath: '/trainers/$id'
      preLoaderRoute: typeof TrainersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$name': {
      id: '/api/media/$name'
      path: '/api/media/$name'
      fullPath: '/api/media/$name'
      preLoaderRoute: typeof ApiMediaNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InboxRouteChildren {
  InboxBookingIdRoute: typeof InboxBookingIdRoute
}

const InboxRouteChildren: InboxRouteChildren = {
  InboxBookingIdRoute: InboxBookingIdRoute,
}

const InboxRouteWithChildren = InboxRoute._addFileChildren(InboxRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BookingsRoute: BookingsRoute,
  DashboardRoute: DashboardRoute,
  EarningsRoute: EarningsRoute,
  InboxRoute: InboxRouteWithChildren,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  OnboardRoute: OnboardRoute,
  SearchRoute: SearchRoute,
  ApiPlaceThumbRoute: ApiPlaceThumbRoute,
  ApiUploadRoute: ApiUploadRoute,
  GymsIdRoute: GymsIdRoute,
  TrainersIdRoute: TrainersIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMediaNameRoute: ApiMediaNameRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
